### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Nuc1eoN** [ShayBox/WindscribeGUI#1]
Hi I am getting

```
$ windscribegui
Traceback (most recent call last):
  File "/usr/sbin/windscribegui", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/windscribegui/main.py", line 35, in main
    Dialog()
  File "/usr/lib/python3.10/site-packages/windscribegui/dialog.py", line 27, in __init__
    self.populate_locations()
  File "/usr/lib/python3.10/site-packages/windscribegui/dialog.py", line 48, in populate_locations
    for location in windscribe.locations():
  File "/usr/lib/python3.10/site-packages/windscribe/main.py", line 142, in locations
    location = Location(*_parse_location(line))
TypeError: Location.__init__() missing 3 required positional arguments: 'short', 'city', and 'label'
```

on Archlinux using the AUR package.

**Comment by ShayBox** [comment]
Seems your windscribe cli may have different output, can you provide the `windscribe locations` output?

**Comment by Nuc1eoN** [comment]
Wait, it depends on windscribe cli? - That is not mentioned anywhere, nor is it a dependency in the AUR package

**Comment by ShayBox** [comment]
Oh yeah, I guess I missed that in the readme, you do have to login via cli.
Windscribe also lets you generate openvpn configs for most computers to use if that's a preferable option, wireguard for pro users
